kernel:
  image: linuxkit/kernel:4.14.90
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:a41f86e8e5ca8552e9ede89a2af705f833aff969
  - linuxkit/runc:83d0edb4552b1a5df1f0976f05f442829eac38fe
  - linuxkit/containerd:326b096cd5fbab0f864e52721d036cade67599d6
  - linuxkit/ca-certificates:v0.6
onboot:
  - name: metadata
    image: linuxkit/metadata:v0.6
  - name: sysctl
    image: linuxkit/sysctl:v0.6
  - name: sysfs
    image: linuxkit/sysfs:v0.6
  - name: format
    image: linuxkit/format:v0.6
  - name: mount
    image: linuxkit/mount:v0.6
    command: ["/usr/bin/mountie", "/var/lib/plex"]
  - name: mount
    image: linuxkit/mount:v0.6
services:
  - name: getty
    image: linuxkit/getty:2eb742cd7a68e14cf50577c02f30147bc406e478
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:v0.6
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.6
  - name: ntpd
    image: linuxkit/openntpd:v0.6
  - name: pms
    # https://hub.docker.com/r/plexinc/pms-docker/tags
    image: plexinc/pms-docker:1.14.1.5488-cc260c476
    capabilities: [all] # todo: refine this
    net: host
    runtime:
      envFromFile:
        TZ: "/run/config/pms/timezone"
        PLEX_CLAIM: "/run/config/pms/plex_claim"
      mkdir:
        - /var/lib/homebox/pms/config
        - /var/lib/homebox/pms/data
        - /var/lib/homebox/pms/transcode
    binds:
      - /etc/resolv.conf:/etc/resolv.conf
      - /var/lib/homebox/pms/config:/config
      - /var/lib/homebox/pms/data:/data
      - /var/lib/homebox/pms/transcode:/transcode
    env:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  - name: dropbox
    image: errordeveloper/dropbox:4648336f9abb9c57710be153e1f10599fd8b9886
    runtime:
      mkdir:
        - /var/lib/homebox/dropbox
    binds:
      - /etc/resolv.conf:/etc/resolv.conf
      - /var/lib/homebox/dropbox:/home/dropbox/Dropbox
files:
  - path: var/lib/homebox
    directory: true
trust:
  org:
    - linuxkit
    - library
