kernel:
  image: linuxkit/kernel:4.14.90
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:b2066f277482d02b8232c7b8520d52a66a7940c3
  - linuxkit/runc:83d0edb4552b1a5df1f0976f05f442829eac38fe
  - linuxkit/containerd:326b096cd5fbab0f864e52721d036cade67599d6
  - linuxkit/ca-certificates:v0.6
onboot:
  - name: metadata
    image: linuxkit/metadata:v0.6
  - name: sysctl
    image: linuxkit/sysctl:v0.6
  - name: sysfs
    image: linuxkit/sysfs:v0.6
  - name: format
    image: linuxkit/format:v0.6
  - name: mount
    image: linuxkit/mount:v0.6
    command: ["/usr/bin/mountie", "/var/lib/homebox"]
  - name: mount
    image: linuxkit/mount:v0.6
services:
  - name: getty
    image: linuxkit/getty:2eb742cd7a68e14cf50577c02f30147bc406e478
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:v0.6
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.6
  - name: ntpd
    image: linuxkit/openntpd:v0.6
  - name: pms
    # https://hub.docker.com/r/plexinc/pms-docker/tags
    image: plexinc/pms-docker:1.14.1.5488-cc260c476
    capabilities: [all] # todo: refine this
    net: host
    runtime:
      envFromFile:
        TZ: "/run/config/pms/timezone"
        PLEX_CLAIM: "/run/config/pms/plex_claim"
      mkdir:
        # TODO: THIS ALSO DOESN'T HAVE ANY EFFECT
        - /var/lib/homebox/pms/config
        - /var/lib/homebox/pms/data
        - /var/lib/homebox/pms/transcode
    binds:
      - /etc/resolv.conf:/etc/resolv.conf
      # this will probably become same as the dropbox dir
      - /var/lib/homebox/pms/data:/data
      # config may get stored in the cotnainer image or metadata
      - /var/lib/homebox/pms/config:/config
      # this may become just tmpfs
      - /var/lib/homebox/pms/transcode:/transcode
    env:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  - name: dbx
    image: errordeveloper/dropbox:5c4ef2c225b8f2b1fccc176d54aaeebd6eb9de3d
    command:
      - /bin/bash
      - -c
      - while true; do sleep 1; done
    runtime:
      # TODO: this doesn't actually work yet we need to find a way to mkdir after bind mount
      mkdir:
        # ensure directory is chowned to have corret gid/uid
        - home/dbx/Dropbox
        # these seem to make it crash when missing
        - home/dbx/Dropbox/.dropbox.cache
        - home/dbx/Dropbox/.dropbox.cache/attrs_cache
        - home/dbx/Dropbox/.dropbox.cache/placeholder_cache
        - home/dbx/Dropbox/.dropbox.cache/prefetch_cache
    binds:
      - /etc/resolv.conf:/etc/resolv.conf
      - /var/lib/homebox/dbx:/home/dbx/Dropbox
files:
  - path: var/lib/homebox
    directory: true
trust:
  org:
    - linuxkit
    - library
