kernel:
  image: errordeveloper/kernel:4.14.94-2bd588b23ab47d4aa37f0eced78f56d335ba3c3c-amd64
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - errordeveloper/init:4cc5d866d0965c324ee34fd9691aa383e82697a6 # https://github.com/linuxkit/linuxkit/pull/3254
  - errordeveloper/zfs-kmod:4.14.94-2bd588b23ab47d4aa37f0eced78f56d335ba3c3c-amd64 # https://github.com/linuxkit/linuxkit/pull/3273
  - linuxkit/runc:83d0edb4552b1a5df1f0976f05f442829eac38fe
  - linuxkit/containerd:326b096cd5fbab0f864e52721d036cade67599d6
  - linuxkit/ca-certificates:v0.6
onboot:
  - name: metadata
    image: linuxkit/metadata:v0.6
  - name: sysctl
    image: linuxkit/sysctl:v0.6
  - name: sysfs
    image: linuxkit/sysfs:v0.6
  - name: modprobe
    image: linuxkit/modprobe:v0.6
    command: ["modprobe", "zfs"]
  - name: zfs
    image: errordeveloper/zfs:3e2170a50107322947f8023df260e7fc3a33f0c0
    capabilities: [CAP_SYS_ADMIN, CAP_CHOWN]
    command:
      - sh
      - -c
      - >
        zpool import homebox ;
        mkdir -p /var/lib/homebox/.pms ;
        mkdir -p /var/lib/homebox/.pms/data ;
        mkdir -p /var/lib/homebox/.pms/config ;
        mkdir -p /var/lib/homebox/.transmission ;
        mkdir -p /var/lib/homebox/.transmission/torrents ;
        mkdir -p /var/lib/homebox/.transmission/resume ;
        mkdir -p /var/lib/homebox/.transmission/blocklist ;
        mkdir -p /var/lib/homebox/Downloads ;
        mkdir -p /var/lib/homebox/Dropbox ;
        mkdir -p /var/lib/homebox/Dropbox/.dropbox.cache ;
        mkdir -p /var/lib/homebox/Dropbox/.dropbox.cache/attrs_cache ;
        mkdir -p /var/lib/homebox/Dropbox/.dropbox.cache/placeholder_cache ;
        mkdir -p /var/lib/homebox/Dropbox/.dropbox.cache/prefetch_cache ;
        chown 1000:100 -R /var/lib/homebox ;
services:
  - name: getty
    image: linuxkit/getty:2eb742cd7a68e14cf50577c02f30147bc406e478
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:v0.6
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.6
  - name: ntpd
    image: linuxkit/openntpd:v0.6
  - name: sshd-root
    image: errordeveloper/sshd-root:ef18b647ec14e9f564e6d1ba4348b849ddb3d25c
  - name: sshd-user
    image: errordeveloper/sshd-user:522aa4f11c165d540a7277840e33bf24608db98f
  - name: pms
    # https://hub.docker.com/r/plexinc/pms-docker/tags
    image: plexinc/pms-docker:1.14.1.5488-cc260c476
    capabilities: [all] # TODO: refine this
    # TODO: move it to bridged network
    net: host
    runtime:
      envFromFiles: # https://github.com/linuxkit/linuxkit/pull/3254
        TZ: "/run/config/pms/timezone"
        PLEX_CLAIM: "/run/config/pms/plex_claim"
    binds:
      - /etc/resolv.conf:/etc/resolv.conf
      # /config has the actual index of the libraries etc
      - /var/lib/homebox/.pms/config:/config
      # /data has misc data and the media library
      - /var/lib/homebox/.pms/data:/data
      - /var/lib/homebox/Downloads:/data/Downloads
      - /var/lib/homebox/Dropbox:/data/Dropbox
    # /transcode can be mounted at tempfs, as keeping it
    # inside the container maybe not be so wise
    # TODO: identify long-term solution
    tmpfs: [/transcode]
    env:
      - PLEX_UID=1000
      - PLEX_GID=100
      - CHANGE_CONFIG_DIR_OWNERSHIP=false
      #- ALLOWED_NETWORKS=192.168.1.0/24,172.16.0.0/16
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  - name: dropbox
    image: errordeveloper/dropbox:a6eead1a675921ff7b9c0d04fb0e35ee7ae3ea29
    net: host
  - name: transmission
    image: errordeveloper/transmission:8be696ce966be7dcd7134d64f7ef365808954cfc
    net: host
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
  - path: var/lib/homebox
    directory: true
trust:
  org:
    - linuxkit
    - library
