kernel:
  image: errordeveloper/kernel:4.14.94-2bd588b23ab47d4aa37f0eced78f56d335ba3c3c-amd64
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - errordeveloper/init:4cc5d866d0965c324ee34fd9691aa383e82697a6 # https://github.com/linuxkit/linuxkit/pull/3254
  - errordeveloper/zfs-kmod:4.14.94-2bd588b23ab47d4aa37f0eced78f56d335ba3c3c-amd64 # https://github.com/linuxkit/linuxkit/pull/3273
  - linuxkit/runc:83d0edb4552b1a5df1f0976f05f442829eac38fe
  - linuxkit/containerd:326b096cd5fbab0f864e52721d036cade67599d6
  - linuxkit/ca-certificates:v0.6
onboot:
  - name: metadata
    image: linuxkit/metadata:v0.6
  - name: sysctl
    image: linuxkit/sysctl:v0.6
  - name: sysfs
    image: linuxkit/sysfs:v0.6
  - name: modprobe
    image: linuxkit/modprobe:v0.6
    command: ["modprobe", "zfs"]
  #- name: format
  #- image: linuxkit/format:v0.6
  #- name: mount
  #  image: linuxkit/mount:v0.6
  #  # TODO: need something more sophisticated here, especially when we decide on storage
  #  capabilities: [CAP_SYS_ADMIN, CAP_CHOWN]
  #  command:
  #    - sh
  #    - -c
  #    - >
  #      mountie /var/lib/homebox ;
  #      mkdir -p /var/lib/homebox/.pms ;
  #      mkdir -p /var/lib/homebox/.pms/data ;
  #      mkdir -p /var/lib/homebox/.pms/config ;
  #      mkdir -p /var/lib/homebox/.transmission ;
  #      mkdir -p /var/lib/homebox/.transmission/torrents ;
  #      mkdir -p /var/lib/homebox/.transmission/resume ;
  #      mkdir -p /var/lib/homebox/.transmission/blocklist ;
  #      mkdir -p /var/lib/homebox/Downloads ;
  #      mkdir -p /var/lib/homebox/Dropbox ;
  #      mkdir -p /var/lib/homebox/Dropbox/.dropbox.cache ;
  #      mkdir -p /var/lib/homebox/Dropbox/.dropbox.cache/attrs_cache ;
  #      mkdir -p /var/lib/homebox/Dropbox/.dropbox.cache/placeholder_cache ;
  #      mkdir -p /var/lib/homebox/Dropbox/.dropbox.cache/prefetch_cache ;
  #      chown 1000:100 -R /var/lib/homebox ;
services:
  - name: getty
    image: linuxkit/getty:2eb742cd7a68e14cf50577c02f30147bc406e478
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:v0.6
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.6
  - name: ntpd
    image: linuxkit/openntpd:v0.6
files:
  - path: var/lib/homebox
    directory: true
trust:
  org:
    - linuxkit
    - library
