kernel:
  image: linuxkit/kernel:4.14.90
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:c563953a2277eb73a89d89f70e4b6dcdcfebc2d1
  - linuxkit/runc:83d0edb4552b1a5df1f0976f05f442829eac38fe
  - linuxkit/containerd:326b096cd5fbab0f864e52721d036cade67599d6
  - linuxkit/ca-certificates:v0.6
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.6
  - name: sysfs
    image: linuxkit/sysfs:v0.6
  - name: format
    image: linuxkit/format:v0.6
  - name: mount
    image: linuxkit/mount:v0.6
    command: ["/usr/bin/mountie", "/var/lib/plex"]
  - name: mount
    image: linuxkit/mount:v0.6
    command:
      - /bin/mkdir
      - /var/lib/plex/config
      - /var/lib/plex/data
      - /var/lib/plex/transcode
services:
  - name: getty
    image: linuxkit/getty:2eb742cd7a68e14cf50577c02f30147bc406e478
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:v0.6
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.6
  - name: ntpd
    image: linuxkit/openntpd:v0.6
  - name: pms
    # https://hub.docker.com/r/plexinc/pms-docker/tags
    image: plexinc/pms-docker:1.14.1.5488-cc260c476
    capabilities: [all]
    net: host
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/lib/plex/config:/config
     - /var/lib/plex/data:/data
     - /var/lib/plex/transcode:/transcode
    #command: []
    env: # use metadata for TZ and PLEX_CLAIM
    - TZ="Europe/London"
      # https://www.plex.tv/claim/
    - PLEX_CLAIM="claim-TuqrocGqLSJLYqgRdwnW"
    # somehow PATH is not the same as with docker run out of the box
    - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
files:
  - path: var/lib/plex
    directory: true
trust:
  org:
    - linuxkit
    - library
