image: sshd-root
config:
  pid: host
  binds:
    - /etc/resolv.conf:/etc/resolv.conf
    - /run:/run
    - /etc:/hostroot/etc
    - /usr/bin/ctr:/usr/bin/ctr
    - /usr/bin/runc:/usr/bin/runc
    - /containers:/containers
    - /var/log:/var/log
    - /var/lib/containerd:/var/lib/containerd
    - /dev:/dev
    - /sys:/sys
    - /var/lib/homebox:/var/lib/homebox
  capabilities:
    - all
